__doc__ = """BECAUSE THERE CAN BE ONLY ONE.
THIS IS A GLOBAL VARIABLE WHICH WILL MESS URRRYYYYYYYYYYYYYYYY...
...
..YYYYYY THING UP IF YOU OVERRIDE, NAME-COLLIDE, OR OTHERWISE fuck WITH IT.

SO DON'T.

UR WELCOME.

"""